# fly.toml file generated for kom-badge-cache on 2022-10-25T22:37:22Z

app = "kom-badge-cache"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  HOST = "0.0.0.0"
  PORT = "3000"
  LOG_LEVEL = "info"
  LOG_FORMAT = "json"


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = "60s"
    method = "get"
    path = "/status"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

